### ISSUE TITLE
ValueError: Length of values does not match length of index

### ISSUE THREAD

**Issue by cartal** [calico/solo#16]
Hi again @njbernstein and @davek44 :)

After the fix from issue #13 `solo` is working really great in some of my samples. Thanks very much! 

However, for some of them, `solo` runs without any problem but just before it's going to report the scores/doublets it fails with the following error:

```
Train accuracy: 0.8743
Test accuracy:  0.8638
Train AUROC: 0.8638
Test AUROC:  0.8553

Traceback (most recent call last):
      File "/nfs/users/nfs_c/ct5/storage/anaconda3/envs/solo/bin/solo", line 11, in <module>
          load_entry_point('solo', 'console_scripts', 'solo')()
      File "/nfs/users/nfs_c/ct5/tools/solo/solo/solo.py", line 390, in main
         adata.obs['is_doublet'] = is_doublet[:num_cells]
      File "/nfs/users/nfs_c/ct5/storage/anaconda3/envs/solo/lib/python3.6/site-packages/pandas/core/frame.py", line 3370, in __setitem__
         self._set_item(key, value)
     File "/nfs/users/nfs_c/ct5/storage/anaconda3/envs/solo/lib/python3.6/site-packages/pandas/core/frame.py", line 3445, in _set_item
        value = self._sanitize_column(key, value)
     File "/nfs/users/nfs_c/ct5/storage/anaconda3/envs/solo/lib/python3.6/site-packages/pandas/core/frame.py", line 3630, in _sanitize_column
       value = sanitize_index(value, self.index, copy=False)
    File "/nfs/users/nfs_c/ct5/storage/anaconda3/envs/solo/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 519, in sanitize_index
      raise ValueError('Length of values does not match length of index')
ValueError: Length of values does not match length of index
```

Now, I understand that the index somehow doesn't match the original object, but there's nothing to be obviously wrong with the original `anndata` object. 

Do you have any ideas?

**Comment by njbernstein** [comment]
@cartal  could you copy and paste or upload the full output of the run? What size is the data? Maybe you can share it with me so I can troubleshoot the issue?

**Comment by cartal** [comment]
Happy to, can you give me an e-mail where I can send the details? 

Thanks!

**Comment by njbernstein** [comment]
nicholas@calicolabs.com is my email address

**Comment by njbernstein** [comment]
@cartal ^

**Comment by cartal** [comment]
@njbernstein done!

**Comment by njbernstein** [comment]
@cartal The issue is that you have two cells with 0 reads in your input data:

```
>>> import anndata
>>> ad = anndata.read("../../../data/H0025_RV.cellbender_filtered.h5ad")
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
>>> ad.X.sum(axis=1)
matrix([[79006.],
        [66248.],
        [54880.],
        ...,
        [  215.],
        [  236.],
        [  219.]], dtype=float32)
>>> sum(ad.X.sum(axis=1) > 0)
matrix([[14998]])
>>> sum(ad.X.sum(axis=1) ==  0)
matrix([[2]])
```

```
/var/spool/slurm/d/job10529374/slurm_script: 12: /var/spool/slurm/d/job10529374/slurm_script: source: not found
[2020-01-09 08:29:15,346] INFO - scvi._settings | Added StreamHandler with custom formatter to 'scvi' logger.
/home/nicholas/miniconda3/envs/solo/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
[2020-01-09 08:29:28,768] INFO - scvi._settings | 'scvi' logger already has a StreamHandler, set its level to 10.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
[2020-01-09 08:29:29,691] WARNING - scvi.dataset.dataset | This dataset has some empty cells, this might fail scVI inference.Data should be filtered with `my_dataset.filter_cells_by_count()
[2020-01-09 08:29:29,717] INFO - scvi.dataset.dataset | Remapping labels to [0,N]
[2020-01-09 08:29:29,717] INFO - scvi.dataset.dataset | Remapping batch_indices to [0,N]
[2020-01-09 08:29:29,773] INFO - scvi.dataset.dataset | Computing the library size for the new data
[2020-01-09 08:29:29,830] INFO - scvi.dataset.dataset | Downsampled from 15000 to 14998 cells
[2020-01-09 08:29:31,263] INFO - scvi.dataset.dataset | Computing the library size for the new data
[2020-01-09 08:29:38,866] DEBUG - scvi.inference.trainer | 
```

Remove those cells and solo should run fine. It did when I ran solo. I'll add an issue to resolve this.

**Comment by cartal** [comment]
This fixed my issue. Thanks!!!
