### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by xnnba** [calico/solo#19]
Hi,

I followed the instruction to run but had follwoing error:

(solo) nxi@server1-X10DAx:/media/nxi/nxi/doublet/real_data$ solo solo.jason, cline-ch.h5ad
[2020-01-15 20:58:03,502] INFO - scvi._settings | Added StreamHandler with custom formatter to 'scvi' logger.
/home/nxi/anaconda3/envs/solo/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
[2020-01-15 20:58:05,545] INFO - scvi._settings | 'scvi' logger already has a StreamHandler, set its level to 10.
Traceback (most recent call last):
  File "/home/nxi/anaconda3/envs/solo/bin/solo", line 8, in <module>
    sys.exit(main())
  File "/home/nxi/anaconda3/envs/solo/lib/python3.6/site-packages/solo/solo.py", line 108, in main
    scvi_data = AnnDatasetFromAnnData(adata)
  File "/home/nxi/anaconda3/envs/solo/lib/python3.6/site-packages/scvi/dataset/anndataset.py", line 40, in __init__
    cell_types=cell_types,
  File "/home/nxi/anaconda3/envs/solo/lib/python3.6/site-packages/scvi/dataset/dataset.py", line 147, in populate_from_data
    else np.zeros((X.shape[0], 1)),
AttributeError: 'NoneType' object has no attribute 'shape'

Could you help resolve it? Thank you!

**Comment by njbernstein** [comment]
Hi @xnnba ,

Sorry I meant to respond earlier. ` solo solo.jason, cline-ch.h5ad` I'm guessing you don't have a comma in your filename. So try ` solo solo.jason cline-ch.h5ad` and let me know how that runs.

**Comment by njbernstein** [comment]
@xnnba  any updates here? otherwise, I'd like to close this out.

**Comment by xnnba** [comment]
> @xnnba any updates here? otherwise, I'd like to close this out.

Thank you for your response. The issue was solved.
