### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by drneavin** [calico/solo#36]
Hello,

I have tried using solo on a few different datasets but have run into the same error with all datasets I have tried:
```
Traceback (most recent call last):
  File "/opt/conda/envs/py36/bin/solo", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/solo/solo.py", line 252, in main
    non_zero_indexes = np.where(singlet_scvi_data.X > 0)
  File "<__array_function__ internals>", line 6, in where
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scipy/sparse/base.py", line 287, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```
The model gets through some of the epochs (usually ~15-30).

solo was installed with pip (python 3.6.8) and is being run out of a singularity bucket. Please let me know if you have any recommendations on how I might fix this or would like additional information.

Thanks,
Drew

**Comment by njbernstein** [comment]
Hi there,

Could you tell me what sort of file type you are feeding into solo? Is it a loom, h5ad, or 10x cell ranger output? 

It seems like the `singlet_scvi_data.X` data type isn't a dense `np.array`, so if you want a quick fix you could do this yourself by ensuring the input expression matrix is a dense `np.array` but Solo should coerce this for you. 

Let me know the file type you are using and input gene expression object type, so I can replicate it on my end and fix the issue or better yet if you can you could share the file with me. I know that's not always possible though.

Best
Nick

**Comment by drneavin** [comment]
Thanks Nick,

I am using the 10x cells ranger outputs (V2 and V3). I haven't QC filtered the data and I suspect that may be contributing to the error? Let me know if you can replicate the error

I'll implement a QC step and retry to see if that solves the issue. Let me know if you identify and resolve the issue on your end in the meantime.

Cheers,
Drew

**Comment by drneavin** [comment]
Any way that this could be updated for the pip install method? I am installing this in a singularity bucket and am receiving the following error when I try to install from github:
```
Warning: Permanently added 'github.com,13.237.44.5' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

However, installation works well with `pip install solo-sc`.

Thanks,
Drew
