### ISSUE TITLE
ValueError: The parameter mu has invalid values

### ISSUE THREAD

**Issue by drneavin** [calico/solo#48]
Hello solo developers,

I am receiving a strange error from solo for one of my pools. I have run the same code for 72 other pools without issue. However, for this pool, I have tried to run 8 times and receive the same error: `ValueError: The parameter mu has invalid values`. This is running from a 10x directory but the data should be pretty good quality (ie no empty dropets, similar number of UMIs and counts to the other pools, low mt%). I have included the full output below. Any idea what might be going wrong here?

```
[2020-08-07 10:21:06,357] INFO - scvi._settings | 'scvi' logger already has a StreamHandler, set its level to 10.
Cuda is not available, switching to cpu running!
[2020-08-07 10:21:06,359] DEBUG - scvi.dataset.dataset10X | Loading extracted local 10X dataset with custom filename
[2020-08-07 10:21:06,359] INFO - scvi.dataset.dataset10X | Preprocessing dataset
[2020-08-07 10:21:25,885] INFO - scvi.dataset.dataset10X | Finished preprocessing dataset
[2020-08-07 10:21:28,177] WARNING - scvi.dataset.dataset | Gene names are not unique.
[2020-08-07 10:21:28,177] INFO - scvi.dataset.dataset | Remapping batch_indices to [0,N]
[2020-08-07 10:21:28,178] INFO - scvi.dataset.dataset | Remapping labels to [0,N]
[2020-08-07 10:21:33,886] INFO - scvi.dataset.dataset | Computing the library size for the new data
[2020-08-07 10:21:34,948] INFO - scvi.dataset.dataset | Downsampled from 17734 to 17734 cells
Min cell depth: 809.0, Max cell depth: 82986.0
[2020-08-07 10:21:35,633] DEBUG - scvi.inference.trainer | 
EPOCH [0/2000]: 
[2020-08-07 10:21:35,633] DEBUG - scvi.inference.trainer | Train Set
[2020-08-07 10:22:01,487] DEBUG - scvi.inference.posterior | ELBO : 28455.5914
[2020-08-07 10:22:26,058] DEBUG - scvi.inference.posterior | Reconstruction Error : 28385.3297
[2020-08-07 10:22:26,059] DEBUG - scvi.inference.trainer | Test Set
[2020-08-07 10:22:28,805] DEBUG - scvi.inference.posterior | ELBO : 27671.6659
[2020-08-07 10:22:31,538] DEBUG - scvi.inference.posterior | Reconstruction Error : 27413.0038
[2020-08-07 10:22:31,538] INFO - scvi.inference.inference | KL warmup for 400 epochs
training:   0%|          | 1/2000 [01:14<41:11:32, 74.18s/it][2020-08-07 10:24:58,636] DEBUG - scvi.inference.trainer | 
EPOCH [2/2000]: 
[2020-08-07 10:24:58,636] DEBUG - scvi.inference.trainer | Train Set
[2020-08-07 10:25:22,855] DEBUG - scvi.inference.posterior | ELBO : 8610.9732
[2020-08-07 10:25:46,947] DEBUG - scvi.inference.posterior | Reconstruction Error : 8240.9735
[2020-08-07 10:25:46,948] DEBUG - scvi.inference.trainer | Test Set
[2020-08-07 10:25:49,655] DEBUG - scvi.inference.posterior | ELBO : 7807.6187
[2020-08-07 10:25:52,310] DEBUG - scvi.inference.posterior | Reconstruction Error : 7437.9775
training:   0%|          | 3/2000 [04:33<47:02:30, 84.80s/it][2020-08-07 10:28:18,850] DEBUG - scvi.inference.trainer | 
EPOCH [4/2000]: 
[2020-08-07 10:28:18,855] DEBUG - scvi.inference.trainer | Train Set
training:   0%|          | 3/2000 [05:56<65:58:41, 118.94s/it]
Traceback (most recent call last):
  File "/opt/conda/envs/py36/bin/solo", line 11, in <module>
    load_entry_point('solo-sc', 'console_scripts', 'solo')()
  File "/opt/solo/solo/solo.py", line 232, in main
    utrainer.train(n_epochs=2000, lr=learning_rate)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/inference/trainer.py", line 182, in train
    if not self.on_epoch_end():
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/inference/trainer.py", line 224, in on_epoch_end
    self.compute_metrics()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/inference/trainer.py", line 137, in compute_metrics
    result = getattr(posterior, metric)()
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/inference/posterior.py", line 251, in elbo
    elbo = compute_elbo(self.model, self)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/models/log_likelihood.py", line 33, in compute_elbo
    **kwargs
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/models/vae.py", line 316, in forward
    reconst_loss = self.get_reconstruction_loss(x, px_rate, px_r, px_dropout)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/models/vae.py", line 219, in get_reconstruction_loss
    -NegativeBinomial(mu=px_rate, theta=px_r).log_prob(x).sum(dim=-1)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/scvi/models/distributions.py", line 95, in __init__
    super().__init__(validate_args=validate_args)
  File "/opt/conda/envs/py36/lib/python3.6/site-packages/torch/distributions/distribution.py", line 36, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter mu has invalid values
```

**Comment by njbernstein** [comment]
That is strange. And look to be an issue with the scVI code we have built off. https://github.com/YosefLab/scVI/pull/663

I don't think they've fixed it yet nor does it look like they are planning to. 
 Things to try:
1. You could try reducing the number of latent variables in your config file.
2. Do some more filtering, particularly cells with lots of UMIs?
Lastly, if you are willing to share the data I could take a stab at it.

**Comment by njbernstein** [comment]
@drneavin  checking in here. Are you still having issues?

**Comment by adamgayoso** [comment]
This is likely due to the library size parameter being too large, which could result from some high outliers in the count matrix. I don't think we need to throw this ValueError here as pytorch has safeguards against this (I think) and we will look into possibly releasing a patch for this. 

That said, like you have suggested, filtering some outliers with very high library size could fix it.

**Comment by drneavin** [comment]
Hi @njbernstein and @adamgayoso. I did try reducing the number of latent variables in the config file in increments down to 12 but couldn't get it to complete. I haven't checked filtering by library size yet - on my to-do list but haven't made time for it yet. I'll let you know once I filter and rerun to let you know if the run completes. Thanks for the recommendations and checking in again.

**Comment by dweemx** [comment]
> That is strange. And look to be an issue with the scVI code we have built off. [YosefLab/scVI#663](https://github.com/YosefLab/scVI/pull/663)
> 
> I don't think they've fixed it yet nor does it look like they are planning to.
> Things to try:
> 
> 1. You could try reducing the number of latent variables in your config file.
> 2. Do some more filtering, particularly cells with lots of UMIs?
>    Lastly, if you are willing to share the data I could take a stab at it.

Also got the same error, reducing the number of latent variable to `32` did solve this issue

What's the impact on reducing this number ? Performance ? Precision ? 
Sorry for this probably naive question (I'm quite new into this field)

**Comment by njbernstein** [comment]
@dweemx sorry for the slow response. I was on vacation. There's a limited effect of Solo's performance with fewer latent variables.

See supplementary figure 14 in our paper: https://www.cell.com/cms/10.1016/j.cels.2020.05.010/attachment/626b1206-08e0-4185-9d7c-92f4546b6b12/mmc1.pdf

**Comment by JeffreyCifello** [comment]
Hello, 

I am receiving the same error raised in this issue but with a slightly different output leading up to the error, most notably starting with ELBO: nan. This error only occurs when the -k option is omitted. 

I have tried reducing the latent variable, number of layers, and eliminating cells with high UMI counts (>10000) as recommended. I tested this on 5,000 cells with <10,000 UMIs below. These have not changed the error. This might stem from the scVI code as mentioned above but I would appreciate additional suggestions. 
```
/home/cifellojp/.local/lib/python3.7/site-packages/scvi/__init__.py:31: DeprecationWarning: scvi is deprecated, please uninstall scvi via `pip uninstall scvi` and install the new scvi-tools package at github                              .com/YosefLab/scvi-tools
  warnings.warn(deprecation_msg, DeprecationWarning)
[2020-12-16 15:47:56,444] INFO - scvi._settings | 'scvi' logger already has a StreamHandler, set its level to 10.
Cuda is not available, switching to cpu running!
[2020-12-16 15:47:56,455] DEBUG - scvi.dataset.dataset10X | Loading extracted local 10X dataset with custom filename
[2020-12-16 15:47:56,455] INFO - scvi.dataset.dataset10X | Preprocessing dataset
[2020-12-16 15:48:05,123] INFO - scvi.dataset.dataset10X | Finished preprocessing dataset
/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3622: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/numpy/core/_methods.py:195: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
[2020-12-16 15:48:05,330] INFO - scvi.dataset.dataset | Remapping labels to [0,N]
[2020-12-16 15:48:05,330] INFO - scvi.dataset.dataset | Remapping batch_indices to [0,N]
[2020-12-16 15:48:06,315] INFO - scvi.dataset.dataset | Computing the library size for the new data
[2020-12-16 15:48:06,461] INFO - scvi.dataset.dataset | Downsampled from 5000 to 5000 cells
Min cell depth: 1001.0, Max cell depth: 9998.0
[2020-12-16 15:48:06,534] DEBUG - scvi.inference.trainer |
EPOCH [0/2000]:
[2020-12-16 15:48:06,534] DEBUG - scvi.inference.trainer | Train Set
[2020-12-16 15:48:13,866] DEBUG - scvi.inference.posterior | ELBO : nan
[2020-12-16 15:48:20,801] DEBUG - scvi.inference.posterior | Reconstruction Error : 36644.7288
[2020-12-16 15:48:20,801] DEBUG - scvi.inference.trainer | Test Set
[2020-12-16 15:48:21,622] DEBUG - scvi.inference.posterior | ELBO : 36996.1680
[2020-12-16 15:48:22,406] DEBUG - scvi.inference.posterior | Reconstruction Error : 36821.7090
[2020-12-16 15:48:22,407] INFO - scvi.inference.inference | KL warmup for 400 epochs
training:   0%|                                                                                                                                                                       | 0/2000 [00:00<?, ?it/s]                              [2020-12-16 15:48:23,694] WARNING - scvi.inference.trainer | Model training loss was NaN
training:   0%|                                                                                                                                                                       | 0/2000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/cifellojp/.local/bin/solo", line 8, in <module>
    sys.exit(main())
  File "/home/cifellojp/.local/lib/python3.7/site-packages/solo/solo.py", line 240, in main
    utrainer.train(n_epochs=2000, lr=learning_rate)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/inference/trainer.py", line 190, in train
    self.on_training_loop(tensors_list)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/inference/trainer.py", line 214, in on_training_loop
    self.current_loss = loss = self.loss(*tensors_list)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/inference/inference.py", line 130, in loss
    sample_batch, local_l_mean, local_l_var, batch_index, y
  File "/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/models/vae.py", line 391, in forward
    reconst_loss = self.get_reconstruction_loss(x, px_rate, px_r, px_dropout)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/models/vae.py", line 282, in get_reconstruction_loss
    -NegativeBinomial(mu=px_rate, theta=px_r).log_prob(x).sum(dim=-1)
  File "/home/cifellojp/.local/lib/python3.7/site-packages/scvi/models/distributions.py", line 114, in __init__
    super().__init__(validate_args=validate_args)
  File "/usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages/torch/distributions/distribution.py", line 36, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter mu has invalid values
```

**Comment by njbernstein** [comment]
@JeffreyCifello Could try loading the data as an h5ad? 

How have you filtered the data? Can you make sure no genes or cells have 0 counts?

**Comment by JeffreyCifello** [comment]
@njbernstein Making sure that no genes or cells have 0 counts appears to have fixed my issue. Loading via 10x works after removing these genes/cells. I used Seurat to keep cells with at least 100 genes and less than 60% mitochondrial genes, and saved these back into a 10x directory using write10xCounts. Thank you for the advice.

**Comment by njbernstein** [comment]
Cool. closing this down

**Comment by njbernstein** [comment]
Do all the genes have counts? If you can send me the h5ad I can help trouble shoot.

**Comment by mmfalco** [comment]
Ok, I found out that in those samples in which the number of cells is < ~500 after filtering this error pops out. So probably not enough data left to run the models.
