### ISSUE TITLE
Running error: "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by mmfalco** [calico/solo#64]
Hi, I'm having the following error for some of my samples:
```
file sample1.loom ; output folder solo_results/sample1
[2021-05-27 13:31:32,706] INFO - scvi._settings | 'scvi' logger already has a StreamHandler, set its level to 10.
Cuda is not available, switching to cpu running!
[2021-05-27 13:31:32,708] INFO - scvi.dataset.loom | Preprocessing dataset

Traceback (most recent call last):
  File "/shared/matiasfa/miniconda2/envs/solo/bin/solo", line 8, in <module>
    sys.exit(main())
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/solo/solo.py", line 114, in main
    scvi_data = LoomDataset(data_path)
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/scvi/dataset/loom.py", line 66, in __init__
    delayed_populating=delayed_populating,
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/scvi/dataset/dataset.py", line 2026, in __init__
    self.populate()
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/scvi/dataset/loom.py", line 88, in populate
    ds = loompy.connect(os.path.join(self.save_path, self.filenames[0]))
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/loompy/loompy.py", line 1389, in connect
    return LoomConnection(filename, mode, validate=validate)
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/loompy/loompy.py", line 81, in __init__
    if not lv.validate(filename):
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/loompy/loom_validator.py", line 48, in validate
    with h5py.File(path, mode="r") as f:
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/shared/matiasfa/miniconda2/envs/solo/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```
The samples are filtered and with similar number of genes and cells as other samples that did run. Any suggestion?

**Comment by njbernstein** [comment]
That's an h5ad issue. Usually it means you are already reading that h5ad with a different process at the same time, which isnt allowed with h5ad

**Comment by mmfalco** [comment]
Thanks or the quick response! indeed seems something like that. I just removed and created again and that seems to have solved the issue. Now I have the mu parameter issue, but as discussed in another [issue]( #48 ) seems to be related to the low number of cells in the sample after filtering. Closing the issue
