### ISSUE TITLE
Error on new solo version

### ISSUE THREAD

**Issue by cnk113** [calico/solo#66]
Hello,

I updated to the newest version on github as well as scvi-tools.
However when I start it fails on the first step:
```
Min cell depth: 500.0, Max cell depth: 40136.0                                                                                                                                                                   
INFO     No batch_key inputted, assuming all cells are same batch                                                                                                                                                
INFO     No label_key inputted, assuming all cells have same label                                                                                                                                               
INFO     Using data from adata.X                                                                                                                                                                                 
INFO     Computing library size prior per batch                                                                                                                                                                  
INFO     Successfully registered anndata object containing 14643 cells, 36601 vars, 1 batches, 1 labels, and 0 proteins. Also registered 0 extra categorical covariates and 0 extra continuous covariates.       
INFO     Please do not further modify adata until model is trained.                                                                                                                                              
GPU available: True, used: True                                                                                                                                                                                  
TPU available: False, using: 0 TPU cores                                                                                                                                                                         
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]                                                                                                                                                                        
Epoch 1/2000:   0%|                                                                                                                                   | 1/2000 
[00:02<1:34:48,  2.85s/it, loss=8.43e+03, v_num=1]
...
  File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
    self.train_loop.run_training_epoch()
  File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 577, in run_training_epoch
    self.trainer.optimizer_connector.update_learning_rates(interval='epoch')
  File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/optimizer_connector.py", line 66, in update_learning_rates
    f'ReduceLROnPlateau conditioned on metric {monitor_key}'
pytorch_lightning.utilities.exceptions.MisconfigurationException: ReduceLROnPlateau conditioned on metric reconstruction_loss_validation which is not available. 
Available metrics are: ['train_loss_step', 'train_loss_epoch', 'train_loss', 'elbo_train', 'reconstruction_loss_train', 'kl_local_train', 'kl_global_train']. 
Condition can be set using `monitor` key in lr scheduler dict
Epoch 1/2000:   0%| 
```

**Comment by njbernstein** [comment]
Hi there,

Thanks for bringing this to my attention. I will try to track down this issue today.

**Comment by njbernstein** [comment]
Hi there

It seems like the most recent version of scvi-tools broke this. Please rollback to
```
pip install scvi-tools==0.11.0
pip install pytorch-lightning==1.2.3
```
I'll be pinning these in the requirements.txt shortly

**Comment by cnk113** [comment]
So I changed the versions as above but now I get this:
```
Min cell depth: 500.0, Max cell depth: 40136.0                                                                                                                                                                   
INFO     No batch_key inputted, assuming all cells are same batch                                                                                                                                                
INFO     No label_key inputted, assuming all cells have same label                                                                                                                                               
INFO     Using data from adata.X                                                                                                                                                                                 
INFO     Computing library size prior per batch                                                                                                                                                                  
INFO     Successfully registered anndata object containing 14643 cells, 36601 vars, 1 batches, 1 labels, and 0 proteins. Also registered 0 extra categorical covariates and 0 extra continuous covariates.       
INFO     Please do not further modify adata until model is trained.                                                                                                                                              
GPU available: True, used: True                                                                                                                                                                                  
TPU available: None, using: 0 TPU cores                                                                                                                                                                          
Epoch 1/2000:   0%|                                                                                                                                                                     | 
0/2000 [00:06<?, ?it/s]Traceback (most recent call last):
File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1102, in call_hook trainer_hook(*args, **kwargs)
File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 85, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module, outputs)
File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/scvi/train/_progress.py", line 89, in on_train_epoch_end
    super().on_train_epoch_end(trainer, pl_module, unused=unused)
TypeError: on_train_epoch_end() got an unexpected keyword argument 'unused'
```

**Comment by njbernstein** [comment]
Very weird. okay lemme try track this down

**Comment by njbernstein** [comment]
Okay try now. After you install the latest version from github in a clean environment could you post the `pip freeze` if you still have issues.

**Comment by cnk113** [comment]
Different error now
```
Min cell depth: 500.0, Max cell depth: 40022.0                                                                                                                                                                   
INFO     No batch_key inputted, assuming all cells are same batch
INFO     No label_key inputted, assuming all cells have same label                                                                                                                                               
INFO     Using data from adata.X
INFO     Computing library size prior per batch                                                                                                                                                              
INFO     Successfully registered anndata object containing 14637 cells, 36601 vars, 1 batches, 1 labels, and 0 proteins. Also registered 0 extra categorical covariates and 0 extra continuous covariates.       
INFO     Please do not further modify adata until model is trained.                                                                                                                                              
GPU available: True, used: True
TPU available: False, using: 0 TPU cores                                                                                                                                                                         
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Epoch 1/2000:   0%|                                                                                                                                   | 1/2000 [00:02<1:34:36,  2.84s/it, loss=7.04e+03, v_num=1]
File "/home/chang/miniconda3/envs/solo/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 871, in run_train
    self.train_loop.run_training_epoch() 
File "/home/chang/miniconda3/envs/solo/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 577, in run_training_epoch
   self.trainer.optimizer_connector.update_learning_rates(interval='epoch')
File "/home/chang/miniconda3/envs/solo/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/optimizer_connector.py", line 66, in update_learning_rates
f'ReduceLROnPlateau conditioned on metric {monitor_key}'
pytorch_lightning.utilities.exceptions.MisconfigurationException: ReduceLROnPlateau conditioned on metric reconstruction_loss_validation which is not available. Available metrics are: ['train_loss_step', 'train_loss_epoch', 'train_loss', 'elbo_train', 'reconstruction_loss_train', 'kl_local_train', 'kl_global_train']. Condition can be set using `monitor` key in lr scheduler dict
Epoch 1/2000:   0%|  
```
pip freeze output
```
absl-py==0.13.0                                                                                                                                                                                         [107/488]aiohttp==3.7.4.post0                                                                                                                                                                                             anndata==0.7.6                                                                                                                                                                                                   argcomplete==1.12.3                                                                                                                                                                                              argon2-cffi==20.1.0                                                                                                                                                                                              async-generator==1.10                                                                                                                                                                                            async-timeout==3.0.1                                                                                                                                                                                             attrs==21.2.0
backcall==0.2.0
bleach==4.0.0
cached-property==1.5.2
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
colorama==0.4.4
commonmark==0.9.1
ConfigArgParse==1.5.2
cycler==0.10.0
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
entrypoints==0.3
et-xmlfile==1.1.0
fsspec==2021.7.0
future==0.18.2
google-auth==1.34.0
google-auth-oauthlib==0.4.5                                                                                                                                                                                      grpcio==1.39.0                                                                                                                                                                                                   h5py==3.3.0                                                                                                                                                                                                      idna==3.2                                                                                                                                                                                                        importlib-metadata==1.7.0
ipykernel==6.1.0
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
joblib==1.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
leidenalg==0.8.7
llvmlite==0.36.0
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mistune==0.8.4
multidict==5.1.0
natsort==7.1.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.6.2
notebook==6.4.3
numba==0.53.1
numexpr==2.7.3
numpy==1.21.1
oauthlib==3.1.1
openpyxl==3.0.7
opt-einsum==3.3.0
packaging==21.0
pandas==1.3.1
pandocfilters==1.4.3
parso==0.8.2
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.1
prometheus-client==0.11.0
prompt-toolkit==3.0.19
protobuf==3.17.3
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyDeprecate==0.3.0
Pygments==2.9.0
pynndescent==0.5.4
pyparsing==2.4.7
pyro-api==0.1.2
pyro-ppl==1.7.0
pyrsistent==0.18.0
python-dateutil==2.8.2                                                                                                                                                                                           python-igraph==0.9.6                                                                                                                                                                                             pytorch-lightning==1.3.8                                                                                                                                                                                         pytz==2021.1                                                                                                                                                                                                     PyYAML==5.4.1                                                                                                                                                                                                    pyzmq==22.2.1                                                                                                                                                                                                    requests==2.26.0                                                                                                                                                                                                 requests-oauthlib==1.3.0                                                                                                                                                                                         rich==10.7.0                                                                                                                                                                                                     rsa==4.7.2                                                                                                                                                                                                       scanpy==1.8.1                                                                                                                                                                                                    scikit-learn==0.24.2                                                                                                                                                                                             scipy==1.7.1                                                                                                                                                                                                     scvi-tools==0.12.2                                                                                                                                                                                               seaborn==0.11.1
Send2Trash==1.8.0
sinfo==0.3.4
six==1.16.0
solo-sc @ file:///home/chang/solo                                                                                                                                                                         [0/488]statsmodels==0.12.2
stdlib-list==0.8.0
tables==3.6.1
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
terminado==0.11.0
testpath==0.5.0
texttable==1.6.4
threadpoolctl==2.2.0
torch==1.9.0
torchmetrics==0.5.0
tornado==6.1
tqdm==4.62.0
traitlets==5.0.5
typing-extensions==3.10.0.0
umap-learn==0.5.1
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
xlrd==1.2.0
yarl==1.6.3
zipp==3.5.0
```

**Comment by njbernstein** [comment]
@cnk113  do a pip install pytorch-lightning=1.3.1 please

**Comment by cnk113** [comment]
It works! Thanks for the fast turnaround.
