### ISSUE TITLE
python 3.6 incompatibility

### ISSUE THREAD

**Issue by drneavin** [calico/solo#69]
Hi there,

I am writing to report an incompatability with pythono 3.6 even thought PyPi indicates that solo-sc v1.0 should be compatible with python 3.6 and the PyPi clone + ve instructions still use python 3.6 (`git clone git@github.com:calico/solo.git && cd solo && conda create -n solo python=3.6 && conda activate solo && pip install -e .`). This is actually due to an incompatibility between scvi-tools and python 3.6 that returns the following error: 

```
Traceback (most recent call last):
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/solo_soup_36a/bin/solo", line 33, in <module>
    sys.exit(load_entry_point('solo-sc', 'console_scripts', 'solo')())
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/solo_soup_36a/bin/solo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/solo_soup_36a/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/directflow/SCCGGroupShare/projects/DrewNeavin/software/anaconda3/envs/solo_soup_36a/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/drenea/solo/solo/solo.py", line 20, in <module>
    from scvi.external import SOLO
ModuleNotFoundError: No module named 'scvi.external'
```

This seems to have been resolved in scvi-tools v0.9.1. However, that requires python >= 3.7. 

I've been trying to install on 3.6 due to requirements of other softwares I want in the same image. Wanted to post here to ask for update in documents and in case others are facing similar error

**Comment by njbernstein** [comment]
Hi there,

Thanks for pointing this out. I'll update the documentation now.

**Comment by drneavin** [comment]
Hi @njbernstein ,

Yes, it seems the github installations instructions both require python 3.7 but PyPi is where I saw python 3.6 in the installation instructions.

Also, on the PyPi page, it indicates the required python version is >= 3.6:
```Requires: Python >=3.6```

Thanks for updating!
