### ISSUE TITLE
Error using h5ad file

### ISSUE THREAD

**Issue by jddavies95** [calico/solo#78]
Hey, I keep getting this error about the object not having the attribute 'loc'. I am using a h5ad file of unnormalized, filtered data exported from scanpy. Do you know what may be causing this? Thanks!

2022-11-23T16:57:41.248186372Z Traceback (most recent call last):
2022-11-23T16:57:41.248381225Z   File "/opt/conda/bin/solo", line 33, in <module>
2022-11-23T16:57:41.249388349Z     sys.exit(load_entry_point('solo-sc', 'console_scripts', 'solo')())
2022-11-23T16:57:41.249686579Z   File "/opt/solo/solo/solo.py", line 319, in main
2022-11-23T16:57:41.249926121Z     doublet_score = softmax_predictions.loc[:, "doublet"]
2022-11-23T16:57:41.252468271Z AttributeError: 'numpy.ndarray' object has no attribute 'loc'

**Comment by davek44** [comment]
Hi, it's confusing for softmax_predictions to be an ndarray rather than a pandas dataframe. You can see here scVI SOLO predict returns a dataframe here: https://github.com/scverse/scvi-tools/blob/main/scvi/external/solo/_model.py#L392. Can you use the python debugger and try to figure out where softmax_predictions becomes an array for you?

**Comment by njbernstein** [comment]
@davek44 close this one two cause we didn't get a follow up?
