### ISSUE TITLE
ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' 

### ISSUE THREAD

**Issue by zznx** [calico/solo#88]
Hi, how do you make software work?

```
solo -h
Traceback (most recent call last):
  File "/root/miniconda3/envs/solo/bin/solo", line 5, in <module>
    from solo.solo import main
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/solo/solo.py", line 17, in <module>
    import scvi
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/__init__.py", line 10, in <module>
    from . import data, model, external
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/model/__init__.py", line 1, in <module>
    from ._autozi import AUTOZI
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/model/_autozi.py", line 12, in <module>
    from scvi.model.base import UnsupervisedTrainingMixin
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/model/base/__init__.py", line 3, in <module>
    from ._pyromixin import PyroJitGuideWarmup, PyroSampleMixin, PyroSviTrainMixin
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/model/base/_pyromixin.py", line 12, in <module>
    from scvi.train import PyroTrainingPlan, TrainRunner
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/train/__init__.py", line 1, in <module>
    from ._trainer import Trainer
  File "/root/miniconda3/envs/solo/lib/python3.12/site-packages/scvi/train/_trainer.py", line 8, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/root/miniconda3/envs/solo/lib/python3.12/site-packages/pytorch_lightning/loggers/__init__.py)
```

```
pip list
Package                  Version
------------------------ -----------
absl-py                  2.1.0
aiohappyeyeballs         2.3.7
aiohttp                  3.10.4
aiosignal                1.3.1
anndata                  0.10.8
array_api_compat         1.8
asttokens                2.4.1
attrs                    24.2.0
chex                     0.1.86
comm                     0.2.2
ConfigArgParse           1.7
contextlib2              21.6.0
contourpy                1.2.1
cycler                   0.12.1
Cython                   0.29.37
decorator                5.1.1
docrep                   0.3.2
et-xmlfile               1.1.0
etils                    1.9.2
executing                2.0.1
filelock                 3.15.4
flax                     0.8.5
fonttools                4.53.1
frozenlist               1.4.1
fsspec                   2024.6.1
future                   1.0.0
grpcio                   1.65.5
h5py                     3.11.0
idna                     3.7
igraph                   0.11.6
importlib_resources      6.4.3
ipython                  8.26.0
ipywidgets               8.1.3
jax                      0.4.31
jaxlib                   0.4.31
jedi                     0.19.1
Jinja2                   3.1.4
joblib                   1.4.2
jupyterlab_widgets       3.0.11
kiwisolver               1.4.5
legacy-api-wrap          1.4
leidenalg                0.10.2
lightning                2.1.4
lightning-utilities      0.11.6
llvmlite                 0.43.0
Markdown                 3.7
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.2
matplotlib-inline        0.1.7
mdurl                    0.1.2
ml_collections           0.1.1
ml-dtypes                0.4.0
mpmath                   1.3.0
msgpack                  1.0.8
mudata                   0.3.0
multidict                6.0.5
multipledispatch         1.0.0
natsort                  8.4.0
nest-asyncio             1.6.0
networkx                 3.3
numba                    0.60.0
numpy                    1.26.4
numpyro                  0.15.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
openpyxl                 3.1.5
opt-einsum               3.3.0
optax                    0.2.3
orbax-checkpoint         0.5.23
packaging                24.1
pandas                   2.2.2
parso                    0.8.4
patsy                    0.5.6
pexpect                  4.9.0
pillow                   10.4.0
pip                      24.2
prompt_toolkit           3.0.47
protobuf                 5.27.3
ptyprocess               0.7.0
pure_eval                0.2.3
pyDeprecate              0.3.0
Pygments                 2.18.0
pynndescent              0.5.13
pyparsing                3.1.2
pyro-api                 0.1.2
pyro-ppl                 1.9.1
python-dateutil          2.9.0.post0
pytorch-lightning        2.2.1
pytz                     2024.1
PyYAML                   5.4.1
rich                     13.7.1
scanpy                   1.10.2
scikit-learn             1.5.1
scipy                    1.14.0
scvi-tools               0.12.0
seaborn                  0.13.2
session_info             1.0.0
setuptools               72.1.0
six                      1.16.0
solo-sc                  1.3
stack-data               0.6.3
statsmodels              0.14.2
stdlib-list              0.10.0
sympy                    1.13.2
tensorboard              2.17.1
tensorboard-data-server  0.7.2
tensorstore              0.1.64
texttable                1.7.0
threadpoolctl            3.5.0
toolz                    0.12.1
torch                    2.4.0
torchmetrics             1.4.1
tqdm                     4.66.5
traitlets                5.14.3
triton                   3.0.0
typing_extensions        4.12.2
tzdata                   2024.1
umap-learn               0.5.6
wcwidth                  0.2.13
Werkzeug                 3.0.3
wheel                    0.43.0
widgetsnbextension       4.0.11
yarl                     1.9.4
zipp                     3.20.0
```

**Comment by davek44** [comment]
I just pushed an update to the requirements that worked for me with the latest anaconda as a base. Try again.
